### ISSUE TITLE
TLS1.2 is not supported in the current implementation

### ISSUE THREAD

**Issue by AndrevdG** [juniinacio/Barracuda.WAF#1]
Powershell by default will use TLS1.0. The Admin page of a WAF should preferably be using TLS1.2.
The attached file should allow for TLS1.0, 1.1 and 1.2 connections.

Cant push changes :(
[Invoke-Api.zip](https://github.com/juniinacio/Barracuda.WAF/files/2098551/Invoke-Api.zip)

**Comment by juniinacio** [comment]
Dear Andre,

I have added your fix in the module, I have also made the module more flexible by not enforcing TLS 1.2, but also all other TLS versions.

See commit: 867e6b54d8297a6f98b6ccfe32f4d9de351722dd

Regards,

Juni
